# Generated by Django 4.2.1 on 2023-06-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CensusFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumeration_area_number', models.CharField(max_length=200)),
                ('building_serial', models.CharField(max_length=200)),
                ('housing_unit_serial_number', models.CharField(max_length=200)),
                ('line_number_respondents', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
