# Generated by Django 4.2.1 on 2023-07-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='agricultural_land',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='agricultural_land_reform',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='aquafarm',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='conveniences',
            field=models.CharField(choices=[('1', 'a. Refrigerator/ freezer'), ('2', 'b. Stove with oven/ gas range'), ('3', 'c. Microwave oven'), ('4', 'd. Washing Machine'), ('5', 'e. Air Conditioner'), ('6', 'f. Electric fan and other cooling equipment')], default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='crop_farm',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='employer_assistance',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='fishing_activity',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='gov_assistance',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='ict_devices',
            field=models.CharField(choices=[('1', 'g. Radio/ radio cassete (AM, PM, and transistor)'), ('2', 'h. Television'), ('3', 'i. CD/ DVD/ VCD'), ('4', 'j. Audio component/ stereo set/ karaoke/ videoke'), ('5', 'k. Landline/ wireless telephone'), ('6', 'l. Mobile phone'), ('7', 'm. Tablet'), ('8', 'n. Personal computer (desktop, laptop, notebook, netbook, and others)')], default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='internet_access',
            field=models.CharField(choices=[('1', 'a. fixed (wired) narrowband/ broadband network [e.g. via Digital Subscriber Line (DSL), cable modem, high speed leased line,<br> fiber-to-the-home/building, powerline/ and other fixed (wired) broadband]'), ('2', 'b. fixed (wireless) broadband network [e.g. via WiMAX and fixed Code Division Multiple Access (CDMA)]'), ('3', 'c. Satelite broadband network'), ('4', 'd. Mobile broadband network [e.g. via handset, card (e.g. integrated Subscriber Identify Module or SIM card) or USB modem]')], default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='internet_use',
            field=models.CharField(choices=[('1', 'a. Home'), ('2', 'b. Work'), ('3', 'c. School'), ('4', "d. Another person's home"), ('5', 'e. Public place'), ('6', 'f. Private establishment'), ('7', 'g. Internet cafe/ computer shop'), ('8', 'h. In mobility')], default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='loans_relatives',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='monthly_rental_house',
            field=models.CharField(choices=[('1', '1. PhP 500 or less'), ('2', '2. PhP 501 - 1,000'), ('3', '3. PhP 1,001 - 1,500'), ('4', '4. PhP 1,501 - 2,000'), ('5', '5. PhP 2,501 - 4,000'), ('6', '6. PhP 4,001 - 6,000'), ('7', '7. PhP 6,001 - 7,500'), ('8', '8. PhP 7,501 - 10,000'), ('9', '9. PhP 10,001 and over')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='other_residential',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='poultry_farm',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='private_bank',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='private_person',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='vehicles',
            field=models.CharField(choices=[('1', 'o. Car/ van/ jeep/ truck'), ('2', 'p. Motorcycle/ motor scooter/ tricycle'), ('3', 'q. Bicycle/ pedicap'), ('4', 'r. Motorized boat/ banca'), ('5', 's. Nonmotorized boat/ banca')], default='', max_length=200, null=True),
        ),
    ]
