# Generated by Django 4.2.1 on 2023-06-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_censusformmodel_household_serial_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRecordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_1', models.DateTimeField(blank=True, max_length=200, null=True)),
                ('time_begin_1', models.DateTimeField(auto_now=True)),
                ('time_ended_1', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
