# Generated by Django 4.2.1 on 2023-06-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_interviewrecordmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterviewRecordModel',
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='date_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='enumerator_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='mode_of_data_collection',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='number_female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='number_male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='number_of_household_member',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='number_of_visit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='result_of_final_visit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='time_begin_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='time_ended_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
