# Generated by Django 4.2.1 on 2023-07-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_interviewrecordmodel_censusformmodel_date_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censusformmodel',
            name='mode_of_data_collection',
            field=models.CharField(choices=[('PAPI', 'PAPI'), ('SAQ', 'SAQ'), ('CAPI', 'CAPI')], default='option1', max_length=4),
        ),
    ]
