# Generated by Django 4.2.1 on 2023-07-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_censusformmodel_mode_of_data_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censusformmodel',
            name='mode_of_data_collection',
            field=models.CharField(choices=[('PAPI', 'PAPI'), ('SAQ', 'SAQ'), ('CAPI', 'CAPI')], default='PAPI', max_length=4),
        ),
    ]
