# Generated by Django 4.2.1 on 2023-07-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_censusnewformmodel_additional_booklet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusnewformmodel',
            name='citizen_1',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='ethnicity_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='health_problem_a_1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='health_problem_b_1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='health_problem_c_1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='health_problem_d_1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='health_problem_e_1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='health_problem_f_1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='other_country_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='religion_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='remarks_3C',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
