# Generated by Django 4.2.1 on 2023-07-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_censusnewformmodel_citizen_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusnewformmodel',
            name='acquisition_of_housing',
            field=models.CharField(choices=[('1', '1. Inherited'), ('2', '2. Gift'), ('3', '3. Company benefit'), ('4', '4. Purchased'), ('5', '5. Other, Specify')], default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='acquisition_of_housing_specify',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='age_firstmarriage_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='agricultural_land',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='agricultural_land_reform',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='aquafarm',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='attend_school_1',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='business_worked_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='children_alive_specificdate_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='children_borned_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='children_still_living_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='conveniences',
            field=models.CharField(choices=[('1', 'a. Refrigerator/ freezer'), ('2', 'b. Stove with oven/ gas range'), ('3', 'c. Microwave oven'), ('4', 'd. Washing Machine'), ('5', 'e. Air Conditioner'), ('6', 'f. Electric fan and other cooling equipment')], default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='crop_farm',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='employer_assistance',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='fishing_activity',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='floor_area_of_housing',
            field=models.CharField(choices=[('1', '1. Less than 5 sq.m. or Less that 54 sq.ft.'), ('2', '2. 5-9 sq.m. or 54-107 sq.ft.'), ('3', '3. 10-19 sq.m. or 108-209 sq.ft.'), ('4', '4. 20-29 sq.m. or 210-317 sq.ft.'), ('5', '5. 30-49 sq.m. or 318-532 sq.ft.'), ('6', '6. 50-69 sq.m. or 533-748 sq.ft.'), ('7', '7. 70-89 sq.m. or 749-963 sq.ft.'), ('8', '8. 90-119 sq.m. or 964-1,286 sq.ft.'), ('9', '9. 120-149 sq.m. or 1,287-1609 sq.ft.'), ('10', '10. 150-199 sq.m. or 1610-2147 sq.ft.'), ('11', '11. 200 sq.m. and over or 2148 sq.ft. and over')], default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='gov_assistance',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='h11_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='h12_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='h14_municipality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='h14_province',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='h3_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='highest_year_completed_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='ict_devices',
            field=models.CharField(choices=[('1', 'g. Radio/ radio cassete (AM, PM, and transistor)'), ('2', 'h. Television'), ('3', 'i. CD/ DVD/ VCD'), ('4', 'j. Audio component/ stereo set/ karaoke/ videoke'), ('5', 'k. Landline/ wireless telephone'), ('6', 'l. Mobile phone'), ('7', 'm. Tablet'), ('8', 'n. Personal computer (desktop, laptop, notebook, netbook, and others)')], default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='internet_access',
            field=models.CharField(choices=[('1', 'a. fixed (wired) narrowband/ broadband network [e.g. via Digital Subscriber Line (DSL), cable modem, high speed leased line,<br> fiber-to-the-home/building, powerline/ and other fixed (wired) broadband]'), ('2', 'b. fixed (wireless) broadband network [e.g. via WiMAX and fixed Code Division Multiple Access (CDMA)]'), ('3', 'c. Satelite broadband network'), ('4', 'd. Mobile broadband network [e.g. via handset, card (e.g. integrated Subscriber Identify Module or SIM card) or USB modem]')], default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='internet_use',
            field=models.CharField(choices=[('1', 'a. Home'), ('2', 'b. Work'), ('3', 'c. School'), ('4', "d. Another person's home"), ('5', 'e. Public place'), ('6', 'f. Private establishment'), ('7', 'g. Internet cafe/ computer shop'), ('8', 'h. In mobility')], default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='kind_of_worker_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='language_specify',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='loans_relatives',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='monthly_rental_house',
            field=models.CharField(choices=[('1', '1. PhP 500 or less'), ('2', '2. PhP 501 - 1,000'), ('3', '3. PhP 1,001 - 1,500'), ('4', '4. PhP 1,501 - 2,000'), ('5', '5. PhP 2,501 - 4,000'), ('6', '6. PhP 4,001 - 6,000'), ('7', '7. PhP 6,001 - 7,500'), ('8', '8. PhP 7,501 - 10,000'), ('9', '9. PhP 10,001 and over')], default='', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='municipality_reside_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='municipality_school_attended_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='municipality_time_birth_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='municipality_work_past12months_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='number_of_floors',
            field=models.CharField(choices=[('1', '1. One floor (e.g. bungalow, including basement/ mezzanine floor)'), ('2', '2. Two floor'), ('3', '3. Three floors'), ('4', '4. Four floors'), ('5', '5. Five to 10 floors'), ('6', '6. 11 floors or more')], default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='other_residential',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='overseas_worker_1',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='poultry_farm',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='private_bank',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='private_person',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='province_reside_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='province_school_attended_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='province_time_birth_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='province_work_past12months_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='read_write_1',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='remarks_3E',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='tenure_status_of_housing',
            field=models.CharField(choices=[('1', '1. Own or owner-like possesion of the house and lot'), ('2', '2. Own house, rent lot'), ('3', '3. Own house, rent-free lot with consent of owner'), ('4', '4. Own house, rent-free lot without consent of owner'), ('5', '5. Rent house/room, including lot'), ('6', '6. Rent-free house and lot with consent of owner'), ('7', '7. Rent-free house and lot without consent of owner')], default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='type_of_building',
            field=models.CharField(choices=[('1', '1. Single house'), ('2', '2. Duplex'), ('3', '3. Apartment/accesories/ rowhouse'), ('4', '4. Condominium/condotel'), ('5', '5. Other multi-unit residential'), ('6', '6. Commercial/industrial/ agricultural (eg. office, factory, barn)'), ('7', '7. Institutional living quarter\t(e.g. hotel, hospital, convent, jail)'), ('8', '8. Other types of building (e.g. bus/trailer, boat, tent), SPECIFY'), ('9', '9. None (e.g. homeless, cart), END INTERVIEW')], default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='type_of_building_specify',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='usual_activity_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='vehicles',
            field=models.CharField(choices=[('1', 'o. Car/ van/ jeep/ truck'), ('2', 'p. Motorcycle/ motor scooter/ tricycle'), ('3', 'q. Bicycle/ pedicap'), ('4', 'r. Motorized boat/ banca'), ('5', 's. Nonmotorized boat/ banca')], default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusnewformmodel',
            name='year_building_built',
            field=models.CharField(choices=[('1', '1. 2020'), ('2', '2. 2019'), ('3', '3. 2018'), ('4', '4. 2017'), ('5', '5. 2016'), ('6', '6. 2011-2015'), ('7', '7. 2001-2010'), ('8', '8. 1991-2000'), ('9', '9. 1981-1990'), ('10', '10. 1980 or earlier'), ('11', "11. Don't know")], default='', max_length=200, null=True),
        ),
    ]
