# Generated by Django 4.2.1 on 2023-07-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_censusformmodel_mode_of_data_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censusformmodel',
            name='date_1',
            field=models.DateField(blank=True, null=True),
        ),
    ]
