# Generated by Django 4.2.1 on 2023-07-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_censusformmodel_date_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censusformmodel',
            name='time_begin_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='censusformmodel',
            name='time_ended_1',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
