# Generated by Django 4.2.1 on 2023-07-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_censusnewformmodel_conveniences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='conveniences',
            field=models.BooleanField(choices=[('1', 'a. Refrigerator/ freezer'), ('2', 'b. Stove with oven/ gas range'), ('3', 'c. Microwave oven'), ('4', 'd. Washing Machine'), ('5', 'e. Air Conditioner'), ('6', 'f. Electric fan and other cooling equipment')], default=False, max_length=200, null=True),
        ),
    ]
