# Generated by Django 4.2.1 on 2023-07-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_censusformmodel_time_begin_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='censusformmodel',
            name='date_1',
        ),
        migrations.RemoveField(
            model_name='censusformmodel',
            name='time_begin_1',
        ),
        migrations.RemoveField(
            model_name='censusformmodel',
            name='time_ended_1',
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='date_time_created_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='date_time_created_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='date_time_created_3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='date_time_ended_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='date_time_ended_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='date_time_ended_3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='result_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='result_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='result_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='result_description_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='result_description_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='result_description_3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
