# Generated by Django 4.2.1 on 2023-07-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_censusformmodel_result_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusformmodel',
            name='appointment_date_time_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='appointment_date_time_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='appointment_date_time_3',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
