# Generated by Django 4.2.1 on 2023-07-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_censusnewformmodel_conveniences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='ict_devices',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='internet_use',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='censusnewformmodel',
            name='vehicles',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
