# Generated by Django 4.2.1 on 2023-07-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_censusformmodel_age_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusformmodel',
            name='additional_booklet',
            field=models.CharField(blank=True, choices=[('1', 'Yes, use additional booklet'), ('2', 'None')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='not_yet_listed',
            field=models.CharField(blank=True, choices=[('1', 'Yes, add to the list'), ('2', 'None')], default='', max_length=4),
        ),
    ]
