# Generated by Django 4.2.1 on 2023-07-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_censusformmodel_additional_booklet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censusformmodel',
            name='birth_registered_1',
            field=models.CharField(blank=True, choices=[('Yes', '1'), ('No', '2')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='censusformmodel',
            name='copy_birthcert_1',
            field=models.CharField(blank=True, choices=[('Yes', '1'), ('No', '2')], default='', max_length=4),
        ),
    ]
