# Generated by Django 4.2.1 on 2023-07-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_censusformmodel_citizen_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusformmodel',
            name='attend_school_1',
            field=models.CharField(blank=True, choices=[('Yes', '1'), ('No', '2')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='highest_year_completed_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='municipality_reside_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='municipality_school_attended_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='municipality_time_birth_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='overseas_worker_1',
            field=models.CharField(blank=True, choices=[('Yes', '1'), ('No', '2')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='province_reside_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='province_school_attended_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='province_time_birth_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='read_write_1',
            field=models.CharField(blank=True, choices=[('Yes', '1'), ('No', '2')], default='', max_length=4),
        ),
    ]
