# Generated by Django 4.2.1 on 2023-07-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_censusformmodel_age_firstmarriage_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censusformmodel',
            name='age_firstmarriage_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='censusformmodel',
            name='children_alive_specificdate_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='censusformmodel',
            name='children_borned_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='censusformmodel',
            name='children_still_living_1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
