# Generated by Django 4.2.1 on 2023-07-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_censusformmodel_age_firstmarriage_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censusformmodel',
            name='attend_school_1',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='censusformmodel',
            name='birth_registered_1',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='censusformmodel',
            name='citizen_1',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='censusformmodel',
            name='copy_birthcert_1',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='censusformmodel',
            name='overseas_worker_1',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='censusformmodel',
            name='read_write_1',
            field=models.CharField(blank=True, choices=[('Yes', '1: YES'), ('No', '2: NO')], default='', max_length=4),
        ),
    ]
