# Generated by Django 4.2.1 on 2023-07-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_censusformmodel_attend_school_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusformmodel',
            name='acquisition_of_housing',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='floor_area_of_housing',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='number_of_floors',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='tenure_status_of_housing',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='type_of_building',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='censusformmodel',
            name='year_building_built',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
