# Generated by Django 4.2.1 on 2023-07-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_censusformmodel_acquisition_of_housing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censusformmodel',
            name='type_of_building',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=200, null=True),
        ),
    ]
