# Generated by Django 4.2.1 on 2023-07-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_censusformmodel_type_of_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censusformmodel',
            name='type_of_building',
            field=models.CharField(choices=[('test', '1 '), ('testing', '2')], max_length=200, null=True),
        ),
    ]
