# Generated by Django 4.2.1 on 2023-07-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_censusformmodel_type_of_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censusformmodel',
            name='number_of_floors',
            field=models.CharField(choices=[('1', '1 One floor (e.g. bungalow, including basement/ mezzanine floor)'), ('2', '2 Two floor'), ('3', '3 Three floors'), ('4', '4 Four floors'), ('5', '5 Five to 10 floors'), ('6', '6 11 floors or more')], default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='censusformmodel',
            name='type_of_building',
            field=models.CharField(choices=[('1', '1 Single house'), ('2', '2 Duplex'), ('3', '3 Apartment/accesories/ rowhouse'), ('4', '4 Condominium/condotel'), ('5', '5 Other multi-unit residential'), ('6', '6 Commercial/industrial/ agricultural (eg. office, factory, barn)'), ('7', '7 Institutional living quarter\t(e.g. hotel, hospital, convent, jail)'), ('8', '8 Other types of building (e.g. bus/trailer, boat, tent), SPECIFY'), ('9', '9 None (e.g. homeless, cart), END INTERVIEW')], default='', max_length=200, null=True),
        ),
    ]
